---
 - name: start apache 
   service:
     name: apache2
     state: started
# - name: Open port 80 for http access
#   firewalld:
#     service: http
#     permanent: true
#     state: enabled
# - name: Restart the firewalld service to load in the firewall changes
#   service: 
#     name: firewalld 
#     state: restarted

